import json
import re
import tomllib
from pathlib import Path


root = Path(__file__).resolve().parents[2]
bi_root = root / "lc-coding" / "bi"
tauri_root = bi_root / "src-tauri"
config_path = tauri_root / "tauri.conf.json"
capability_dir = tauri_root / "capabilities"

assert config_path.is_file(), "missing Tauri desktop configuration"
config = json.loads(config_path.read_text(encoding="utf-8"))
assert config["productName"] == "LCCoding"
assert config["version"] == "2.3.0"
assert config["identifier"] == "com.lccoding.desktop"
assert config["build"] == {"frontendDist": "../dist"}
assert config["plugins"] == {}

app = config["app"]
assert app["withGlobalTauri"] is False
assert len(app["windows"]) == 1
window = app["windows"][0]
assert window == {
    "label": "main",
    "title": "LCCoding BI",
    "url": "index.html",
    "create": False,
    "width": 300,
    "height": 480,
    "resizable": False,
    "maximizable": False,
    "minimizable": True,
    "closable": True,
    "decorations": True,
    "dragDropEnabled": False,
    "devtools": False,
}

security = app["security"]
assert security["capabilities"] == ["main"]
assert security["freezePrototype"] is True
assert security["dangerousDisableAssetCspModification"] is False
assert security["assetProtocol"] == {"enable": False, "scope": []}
expected_csp = {
    "default-src": {"'self'"},
    "script-src": {"'self'"},
    "style-src": {"'self'"},
    "img-src": {"'self'"},
    "font-src": {"'self'"},
    "connect-src": {"ipc:", "http://ipc.localhost"},
    "object-src": {"'none'"},
    "base-uri": {"'none'"},
    "frame-src": {"'none'"},
    "form-action": {"'none'"},
}
actual_csp = {}
for raw_directive in security["csp"].split(";"):
    parts = raw_directive.strip().split()
    if parts:
        actual_csp[parts[0]] = set(parts[1:])
assert actual_csp == expected_csp

bundle = config["bundle"]
assert bundle["active"] is False
assert bundle["createUpdaterArtifacts"] is False
assert bundle["icon"] == ["icons/icon.ico"]
assert bundle["windows"] == {"webviewInstallMode": {"type": "skip"}}
assert (tauri_root / "icons" / "icon.ico").is_file()
assert (tauri_root / "icons" / "icon.svg").is_file()

capability_files = sorted(path.name for path in capability_dir.glob("*.json"))
assert capability_files == ["main.json"]
capability = json.loads((capability_dir / "main.json").read_text(encoding="utf-8"))
assert capability["identifier"] == "main"
assert capability["windows"] == ["main"]
assert "remote" not in capability
assert capability["permissions"] == ["allow-is-pinned", "allow-set-pinned"]

permission_dir = tauri_root / "permissions" / "autogenerated"
permission_files = sorted(path.name for path in permission_dir.glob("*.toml"))
assert permission_files == ["is_pinned.toml", "set_pinned.toml"]
for command in ("is_pinned", "set_pinned"):
    permissions = tomllib.loads(
        (permission_dir / f"{command}.toml").read_text(encoding="utf-8")
    )["permission"]
    assert permissions == [
        {
            "identifier": f"allow-{command.replace('_', '-')}",
            "description": (
                f"Enables the {command} command without any pre-configured scope."
            ),
            "commands": {"allow": [command]},
        },
        {
            "identifier": f"deny-{command.replace('_', '-')}",
            "description": (
                f"Denies the {command} command without any pre-configured scope."
            ),
            "commands": {"deny": [command]},
        },
    ]

build_rs = (tauri_root / "build.rs").read_text(encoding="utf-8")
library_rs = (tauri_root / "src" / "lib.rs").read_text(encoding="utf-8")
main_rs = (tauri_root / "src" / "main.rs").read_text(encoding="utf-8")
assert re.search(
    r'AppManifest::new\(\)\.commands\(&\[\s*"is_pinned",\s*"set_pinned"\s*\]\)',
    build_rs,
)
handler = re.search(r"generate_handler!\[(?P<commands>[^]]+)\]", library_rs)
assert handler is not None
handler_commands = [
    value.strip().removeprefix("pin::")
    for value in handler.group("commands").split(",")
    if value.strip()
]
assert handler_commands == ["is_pinned", "set_pinned"]
assert "get_snapshot" not in build_rs + library_rs
assert "tauri::webview_version()" in library_rs
assert "BI_WEBVIEW_UNAVAILABLE" in library_rs
assert "WebviewWindowBuilder::from_config" in library_rs
assert ".on_navigation(" in library_rs
assert ".on_download(" in library_rs
assert ".on_new_window(" in library_rs
assert "NewWindowResponse::Deny" in library_rs
assert "lccoding::run();" in main_rs
assert 'windows_subsystem = "windows"' in main_rs

cargo = tomllib.loads((tauri_root / "Cargo.toml").read_text(encoding="utf-8"))
assert cargo["package"] == {
    "name": "lccoding",
    "version": "2.3.0",
    "edition": "2024",
    "rust-version": "1.96",
    "publish": False,
}
assert cargo["dependencies"] == {
    "tauri": {
        "version": "=2.11.5",
        "default-features": False,
        "features": ["common-controls-v6", "compression", "wry"],
    }
}
assert cargo["build-dependencies"] == {
    "tauri-build": {"version": "=2.6.3", "features": []}
}

for forbidden_output in ("node_modules", "dist", "target"):
    assert not (bi_root / forbidden_output).exists()
assert not (tauri_root / "target").exists()
