[package]
name = "lccoding"
version = "2.4.1"
edition = "2024"
rust-version = "1.96"
publish = false

[lib]
name = "lccoding"
path = "src/lib.rs"

[[bin]]
name = "lccoding"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", default-features = false, features = ["common-controls-v6", "compression", "wry"] }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
